export const cleanText=v=>String(v??'').replace(/\u00a0/g,' ').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[\r\n\t]+/g,' ').replace(/\s+/g,' ').trim();
export const cleanSubject=v=>cleanText(v).replace(/[–—−]/g,'-').replace(/^дисциплина\s*[:.-]?\s*/i,'').replace(/\b(?:лекция|практическое занятие|практика|пз|лабораторная работа|лабораторная|семинар(?:ское занятие)?)\b/ig,' ').replace(/\s*\*+\s*$/,'').replace(/\s+([,.;:])/g,'$1').replace(/\s{2,}/g,' ').replace(/^[\s,.;:|/\-–—]+|[\s,.;:|/\-–—]+$/g,'').trim();
export const cleanLocation=v=>cleanText(v).replace(/\bаудитория\s*/ig,'ауд. ').replace(/(?:^|\s)ауд(?:итория)?\.?\s*/i,'ауд. ').replace(/\s*,\s*,+/g,',').replace(/\s*\/\s*/g,' / ');
export const cleanTeacher=v=>cleanText(v).replace(/^(преподаватель|преп\.|доцент|профессор|ассистент)\s*:?[ ]*/i,'').replace(/\s*[,;|]+\s*/g,', ');
export const normalizeGroup=v=>cleanText(v).replace(/^учебная\s+группа\s*/i,'').replace(/^группа\s*/i,'').toUpperCase().replace(/\s+/g,'');
export const normalizeGroupList=value=>{const raw=cleanText(value).replace(/[–—−]/g,'-');if(!raw)return[];const chunks=raw.split(/[,;/|]+/).map(x=>x.trim()).filter(Boolean);const out=[];for(const chunk of chunks){const range=chunk.match(/^(\d{3,4}[А-ЯA-Z]{0,3})\s*-\s*(\d{3,4}[А-ЯA-Z]{0,3})$/i);if(!range){const tokens=[...chunk.matchAll(/(?:^|[^0-9А-ЯA-Zа-яa-z])([0-9]{3,4}[А-ЯA-ZА-Я]{0,3})(?=$|[^0-9А-ЯA-Zа-яa-z])/gi)].map(m=>normalizeGroup(m[1]));if(tokens.length){out.push(...tokens);continue;}const normalized=normalizeGroup(chunk);if(/^\d{3,4}[А-ЯA-Z]{0,3}$/i.test(normalized))out.push(normalized);continue;}const a=range[1].match(/\d+/)?.[0],b=range[2].match(/\d+/)?.[0];const sa=a?range[1].replace(a,'').toUpperCase():'',sb=b?range[2].replace(b,'').toUpperCase():'';const from=Number(a),to=Number(b);if(!a||!b||from>to||to-from>200){out.push(normalizeGroup(chunk));continue;}const suffix=sa===sb?sa:'';for(let n=from;n<=to;n++)out.push(`${n}${suffix}`);}return[...new Set(out.filter(Boolean))];};

export const normalizeStream=v=>{const s=cleanText(v).toUpperCase().replace(/А/g,'A').replace(/Б/g,'B');if(/(?:^|\s)ПОТОК\s*A\b/.test(s)||s==='A')return'A';if(/(?:^|\s)ПОТОК\s*B\b/.test(s)||s==='B')return'B';return null;};
export const normalizeHalf=v=>{const t=cleanText(v).toLowerCase();if(/1\s*\/\s*2|числител/.test(t))return'1/2';if(/2\s*\/\s*2|знаменател/.test(t))return'2/2';return undefined};
export const typeFrom=(v,subject='')=>{const s=`${cleanText(v)} ${cleanText(subject)}`.toLowerCase();if(/лекц/.test(s))return'lecture';if(/лаб/.test(s))return'lab';if(/экзам|зач[её]т|аттест|коллок|контрол/.test(s))return'assessment';if(/пз|практи|семинар/.test(s))return'practice';return'other';};
export const timeRange=v=>{const s=cleanText(v).replace(/[–—−]/g,'-'),m=[...s.matchAll(/(\d{1,2})\s*[:.]\s*(\d{2})/g)];if(m.length<2)return null;const explicit=/(\d{1,2})\s*[:.]\s*(\d{2})\s*(?:-|до)\s*(\d{1,2})\s*[:.]\s*(\d{2})/i.test(s),colon=m.slice(0,2).some(x=>x[0]?.includes(':'));if(!explicit&&!colon)return null;const a=Number(m[0][1]),b=Number(m[0][2]),c=Number(m[1][1]),d=Number(m[1][2]);if(a>23||c>23||b>59||d>59)return null;const start=`${String(a).padStart(2,'0')}:${String(b).padStart(2,'0')}`,end=`${String(c).padStart(2,'0')}:${String(d).padStart(2,'0')}`;return start<end?{start,end}:null;};
export const isoDate=v=>{const s=cleanText(v);const valid=(y,m,d)=>{if(y<2020||y>2035||m<1||m>12||d<1||d>31)return false;const dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d;};const a=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);if(a&&valid(Number(a[3]),Number(a[2]),Number(a[1])))return`${a[3]}-${String(Number(a[2])).padStart(2,'0')}-${String(Number(a[1])).padStart(2,'0')}`;const b=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return b&&valid(Number(b[1]),Number(b[2]),Number(b[3]))?s:null;};
export const weekSpec=v=>{const s=cleanText(v).replace(/[–—−]/g,'-').replace(/\b[12]\s*\/\s*2\b/g,' '),out=[];for(const m of s.matchAll(/\b(\d{1,2})\s*-\s*(\d{1,2})\b/g)){let a=+m[1],b=+m[2];if(a>0&&b>=a&&b-a<=40)for(let n=a;n<=b;n++)out.push(n)}for(const m of s.matchAll(/\b\d{1,2}\b/g))out.push(+m[0]);return[...new Set(out.filter(n=>n>0&&n<=52))].sort((a,b)=>a-b);};

export const parseWeekSpec=weekSpec;
