import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {SOURCES,STUDENT_PAGE,LIVE_LD_JSON,programNames} from './source-registry.mjs';
import {normalizeGroup,normalizeGroupList,cleanSubject,cleanLocation,cleanTeacher,normalizeStream,normalizeHalf,isoDate,timeRange,typeFrom} from './normalize.mjs';
import {parseSourceBuffer} from './source-parser.mjs';
import {RedisScheduleCache} from './redis-cache.mjs';

const STORAGE=join(process.cwd(),'storage','snapshots');const memory=new Map();
let redisPromise;
async function redisCache(){if(!process.env.REDIS_URL)return null;if(!redisPromise){redisPromise=(async()=>{try{const {createClient}=await import('redis');const client=createClient({url:process.env.REDIS_URL});client.on('error',()=>{});await client.connect();return new RedisScheduleCache(client);}catch{return null;}})();}return redisPromise;}

export function sourcesFor(program,course){return SOURCES.filter(s=>s.program===program&&s.course===course);}
export function available(program,course){const sources=sourcesFor(program,course);return {published:sources.filter(s=>['published','verified'].includes(s.status)),quarantined:sources.filter(s=>s.status==='quarantined')};}
export async function loadSchedule(program,course,{forceRefresh=false}={}){const key=`${program}:${course}`;const mem=memory.get(key);if(!forceRefresh&&mem&&Date.now()-mem.cachedAt<10*60*1000)return mem.result;const external=await redisCache();if(!forceRefresh&&external){const cached=await external.get(key);if(cached){memory.set(key,{cachedAt:Date.now(),result:cached});return cached;}}const disk=await readSnapshot(key);if(!forceRefresh&&disk&&Date.now()-disk.cachedAt<6*60*60*1000){memory.set(key,{cachedAt:Date.now(),result:disk.result});return disk.result;}
 if(program==='31.05.01'){try{const result=await loadLiveLd(program,course);await saveSnapshot(key,result);return result;}catch(err){if(disk)return {...disk.result,status:'cache',message:`Live источник недоступен. Показан последний snapshot: ${err.message}`};return {status:'error',events:[],issues:[String(err.message)],message:'Live источник недоступен. Запустите API повторно.'};}}
 const {published,quarantined}=available(program,course);if(!published.length){return{status:'unavailable',events:[],issues:['NO_PUBLISHED_SOURCE'],message:`Официальное расписание ${programNames[program]}, ${course} курса, сейчас не опубликовано на странице кабинета студента.`,sourceUrl:STUDENT_PAGE};}
 const events=[];const issues=[];for(const source of published){try{const r=await fetchSource(source);const safe=r.events.filter(e=>e.program===program&&e.course===course);events.push(...safe);issues.push(...(r.warnings??[]));}catch(err){issues.push(`${source.title}: ${err.message}`);}}
 const unique=dedupe(events);const hasQuarantine=quarantined.length>0;const status=unique.length&&issues.length?'partial':unique.length&&hasQuarantine?'partial':unique.length?'live':'error';const result={status,events:unique,issues,sourceUrl:published[0]?.url??quarantined[0]?.url??STUDENT_PAGE,sourceName:published.map(s=>s.title).join(' · '),message:unique.length?`${unique.length} событий. Источников: ${published.length}.${hasQuarantine?' Часть официальных источников проходит карантин и не публикуется.':''}`:`Не удалось получить подтверждённые события. ${issues.join(' ')}`};if(unique.length)await saveSnapshot(key,result);return result;}
async function loadLiveLd(program,course){const res=await fetch(LIVE_LD_JSON,{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();if(typeof payload?.schemaVersion!=='number'||!payload?.courses)throw new Error('Invalid official JSON schema');const events=[];for(const [key,data] of Object.entries(payload.courses??{})){if(Number(key)!==course)continue;for(const raw of Array.isArray(data.events)?data.events:[]){const date=isoDate(raw.date??raw.dateHint??'');const tr=timeRange(`${raw.start??''} ${raw.end??''}`)||timeRange(raw.time);const subject=cleanSubject(raw.subject??raw.discipline??raw.name);if(!date||!tr||!subject)continue;const groups=normalizeGroupList(raw.groups??raw.group);const stream=normalizeStream(raw.stream);if(!groups.length&&!stream)continue;const visibleGroups=groups.length?groups:['_ALL_'];for(const groupValue of visibleGroups){const group=groupValue==='_ALL_'?'ALL':normalizeGroup(groupValue);events.push({id:String(raw.id??`${program}-${course}-${group}-${date}-${tr.start}-${subject}-${events.length}`),program,course,group,stream,date,start:tr.start,end:tr.end,subject,location:cleanLocation(raw.location),teacher:cleanTeacher(raw.teacher),type:typeFrom(raw.type,subject),half:normalizeHalf(raw.half),weeks:raw.weekNumber?`нед. ${Array.isArray(raw.weekNumber)?raw.weekNumber.join(', '):String(raw.weekNumber)}`:undefined,sourceUrl:LIVE_LD_JSON,sourceTitle:'official-schedules.json',sourceKind:'live-json',confidence:1});}}}return{status:'live',events:dedupe(events),generatedAt:payload.generatedAt,sourceUrl:LIVE_LD_JSON,sourceName:'official-schedules.json',issues:[],message:`Live snapshot ${payload.generatedAt??''}`};}
async function fetchSource(source){const res=await fetch(source.url,{redirect:'follow',signal:AbortSignal.timeout(30000),headers:{accept:'application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/html;q=0.9,*/*;q=0.1'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const declared=source.kind==='official-pdf'?'pdf':source.kind==='official-xlsx'?'xlsx':'html';const buffer=Buffer.from(await res.arrayBuffer());return parseSourceBuffer(buffer,{program:source.program,course:source.course,source},declared);}
export function dedupe(events){const map=new Map();for(const e of events){const key=[e.program,e.course,e.group,e.stream??'',e.date,e.start,e.end,e.subject.toLowerCase(),e.location.toLowerCase(),e.type,e.half??''].join('|');const p=map.get(key);if(!p||(e.confidence??0)>(p.confidence??0))map.set(key,e);}return[...map.values()];}
async function readSnapshot(key){try{return JSON.parse(await readFile(join(STORAGE,`${key.replace(/[^a-z0-9:.\-]/gi,'_')}.json`),'utf8'));}catch{return null;}}
async function saveSnapshot(key,result){await mkdir(STORAGE,{recursive:true});const file=join(STORAGE,`${key.replace(/[^a-z0-9:.\-]/gi,'_')}.json`);const tmp=`${file}.tmp`;const payload={cachedAt:Date.now(),result};await writeFile(tmp,JSON.stringify(payload));await rename(tmp,file);memory.set(key,{cachedAt:Date.now(),result});const external=await redisCache();if(external)await external.set(key,result,6*60*60*1000);}
