import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {join,normalize as normalizePath,extname} from 'node:path';
import {loadSchedule} from './pipeline.mjs';
import {parseSourceBuffer} from './source-parser.mjs';

const ROOT=join(process.cwd(),'dist');const MAX_BODY=15*1024*1024;const rateBuckets=new Map();
const TYPES={'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.json':'application/json;charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.txt':'text/plain;charset=utf-8'};
function send(res,status,body,type='application/json;charset=utf-8',extra={}){const cacheable=status===200&&type!=='application/json;charset=utf-8'&&type!=='text/html;charset=utf-8';res.writeHead(status,{'content-type':type,'cache-control':cacheable?'public, max-age=3600, stale-while-revalidate=86400':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-frame-options':'SAMEORIGIN','permissions-policy':'geolocation=(),camera=(),microphone=()','content-security-policy':"default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://raw.githubusercontent.com; worker-src 'self'; manifest-src 'self'",...extra});res.end(body);}
function clientKey(req){return `${req.socket.remoteAddress??'unknown'}:${req.headers['x-forwarded-for']??''}`;}
function allowRate(req,key,limit,windowMs){const now=Date.now(),bucketKey=`${key}:${clientKey(req)}`,current=rateBuckets.get(bucketKey);if(!current||now-current.startedAt>=windowMs){rateBuckets.set(bucketKey,{startedAt:now,count:1});return true;}if(current.count>=limit)return false;current.count++;return true;}
setInterval(()=>{const cutoff=Date.now()-10*60*1000;for(const [k,v] of rateBuckets)if(v.startedAt<cutoff)rateBuckets.delete(k);},60*1000).unref();
function safeFile(urlPath){const rel=urlPath==='/'?'index.html':urlPath.replace(/^\/+/,'');const file=normalizePath(join(ROOT,rel));return file===ROOT||file.startsWith(`${ROOT}/`)?file:null;}
const server=createServer(async(req,res)=>{try{const u=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);if(u.pathname==='/api/health'){if(req.method!=='GET')return send(res,405,JSON.stringify({error:'Method not allowed'}));return send(res,200,JSON.stringify({ok:true,service:'almazov-schedule-hub',time:new Date().toISOString()}));}
 if(u.pathname==='/api/schedule'&&req.method==='GET'){if(!allowRate(req,'schedule',120,60_000))return send(res,429,JSON.stringify({error:'Слишком много запросов. Повторите позже.'}),undefined,{'retry-after':'60'});const program=u.searchParams.get('program');const course=Number(u.searchParams.get('course'));if(!['31.05.01','31.05.02','37.05.01'].includes(program)||course<1||course>6)return send(res,400,JSON.stringify({error:'Некорректная программа или курс'}));const result=await loadSchedule(program,course);return send(res,200,JSON.stringify(result));}
 if(u.pathname==='/api/import'&&req.method==='POST'){if(!allowRate(req,'import',10,10*60_000))return send(res,429,JSON.stringify({error:'Слишком много импортов. Повторите позже.'}),undefined,{'retry-after':'600'});const contentLength=Number(req.headers['content-length']??0);if(Number.isFinite(contentLength)&&contentLength>MAX_BODY)return send(res,413,JSON.stringify({error:'Файл слишком большой'}));const fileName=(req.headers['x-file-name']??'upload.bin').toString();const program=u.searchParams.get('program');const course=Number(u.searchParams.get('course'));if(!['31.05.01','31.05.02','37.05.01'].includes(program)||course<1||course>6)return send(res,400,JSON.stringify({error:'program/course required'}));const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw Object.assign(new Error('Файл слишком большой'),{statusCode:413});chunks.push(chunk);}const data=Buffer.concat(chunks);const ext=extname(fileName).toLowerCase();const declared=ext==='.pdf'?'pdf':(ext==='.xlsx'||ext==='.xls')?'xlsx':(ext==='.html'||ext==='.htm')?'html':null;if(!declared)return send(res,415,JSON.stringify({error:'Поддерживаются PDF, XLSX/XLS и HTML'}));const source={url:'upload://local',title:`Локальный импорт: ${fileName}`,program,course,stream:null};const parsed=await parseSourceBuffer(data,{program,course,source},declared);const valid=parsed.events.filter(e=>e.date&&e.start&&e.end&&e.subject&&e.group);return send(res,200,JSON.stringify({status:valid.length?'partial':'error',events:valid,issues:parsed.warnings??[],message:`Импортировано кандидатов: ${valid.length}. Перед публикацией запустите validate/commit.`,file:fileName}));}
 if(req.method!=='GET')return send(res,405,JSON.stringify({error:'Method not allowed'}));const file=safeFile(decodeURIComponent(u.pathname));if(!file)return send(res,403,JSON.stringify({error:'Forbidden'}));let info;try{info=await stat(file);}catch{return send(res,404,JSON.stringify({error:'Not found'}));}const body=await readFile(info.isDirectory()?join(file,'index.html'):file);return send(res,200,body,TYPES[extname(file)]??'application/octet-stream');
}catch(err){const status=Number(err?.statusCode??500);send(res,status,JSON.stringify({error:err instanceof Error?err.message:'Internal server error'}));}});
const port=Number(process.env.PORT??4173);const host=process.env.HOST??'0.0.0.0';server.listen(port,host);
