import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {database} from './db.mjs';

const ATTACHMENTS_DIR=resolve(process.env.APP_ATTACHMENTS_DIR??join(process.cwd(),'storage','attachments'));
const MAX_TOTAL=8*1024*1024, MAX_ONE=3*1024*1024;
const CATEGORIES=new Set(['schedule','account','notifications','technical','other']);
const PRIORITIES=new Set(['low','normal','high','urgent']);
const STATUSES=new Set(['new','in_progress','waiting_user','resolved','closed']);
function user(id){if(!id||typeof id!=='string'||id.length<10||id.length>128)throw Object.assign(new Error('Требуется идентификатор пользователя'),{statusCode:401});return id;}
function ticketNumber(){const d=new Date();const suffix=Math.random().toString(36).slice(2,8).toUpperCase();return `ALM-${d.getUTCFullYear()}-${suffix}`;}
function rowTicket(r){return{id:r.id,number:r.number,subject:r.subject,category:r.category,priority:r.priority,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at};}
export async function listTickets(ownerId){const db=await database();ownerId=user(ownerId);return db.prepare('SELECT * FROM support_tickets WHERE owner_id=? ORDER BY updated_at DESC').all(ownerId).map(rowTicket);}
export async function getTicket(ownerId,id){const db=await database();ownerId=user(ownerId);const t=db.prepare('SELECT * FROM support_tickets WHERE id=? AND owner_id=?').get(id,ownerId);if(!t)throw Object.assign(new Error('Обращение не найдено'),{statusCode:404});const messages=db.prepare('SELECT * FROM support_messages WHERE ticket_id=? ORDER BY created_at ASC').all(id).map(m=>({id:m.id,authorType:m.author_type,body:m.body,createdAt:m.created_at}));const attachments=db.prepare('SELECT * FROM support_attachments WHERE ticket_id=? ORDER BY created_at ASC').all(id).map(a=>({id:a.id,name:a.original_name,type:a.mime_type,size:a.size_bytes,downloadUrl:`/api/support/attachments/${a.id}`}));return {...rowTicket(t),messages,attachments};}
export async function createTicket(ownerId,input){const db=await database();ownerId=user(ownerId);const subject=String(input?.subject??'').trim();const description=String(input?.description??'').trim();const category=String(input?.category??'other');const priority=String(input?.priority??'normal');if(subject.length<3||subject.length>180)throw Object.assign(new Error('Тема должна содержать от 3 до 180 символов'),{statusCode:422});if(description.length<5||description.length>10000)throw Object.assign(new Error('Описание должно содержать от 5 до 10000 символов'),{statusCode:422});if(!CATEGORIES.has(category)||!PRIORITIES.has(priority))throw Object.assign(new Error('Некорректные категория или приоритет'),{statusCode:422});const now=new Date().toISOString();const id=randomUUID();const number=ticketNumber();db.prepare('INSERT INTO support_tickets(id,owner_id,number,subject,category,priority,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,ownerId,number,subject,category,priority,'new',now,now);const messageId=randomUUID();db.prepare('INSERT INTO support_messages(id,ticket_id,author_type,body,created_at) VALUES(?,?,?,?,?)').run(messageId,id,'user',description,now);await saveAttachments(db,id,messageId,Array.isArray(input?.attachments)?input.attachments:[]);return getTicket(ownerId,id);}
export async function addMessage(ownerId,id,body){const db=await database();ownerId=user(ownerId);const t=db.prepare('SELECT * FROM support_tickets WHERE id=? AND owner_id=?').get(id,ownerId);if(!t)throw Object.assign(new Error('Обращение не найдено'),{statusCode:404});const text=String(body??'').trim();if(text.length<1||text.length>10000)throw Object.assign(new Error('Сообщение должно содержать от 1 до 10000 символов'),{statusCode:422});const now=new Date().toISOString();const mid=randomUUID();db.prepare('INSERT INTO support_messages(id,ticket_id,author_type,body,created_at) VALUES(?,?,?,?,?)').run(mid,id,'user',text,now);if(t.status==='waiting_user')db.prepare('UPDATE support_tickets SET status=?,updated_at=? WHERE id=?').run('in_progress',now,id);return getTicket(ownerId,id);}
async function saveAttachments(db,ticketId,messageId,list){if(!list.length)return;let total=0;await mkdir(ATTACHMENTS_DIR,{recursive:true});for(const raw of list.slice(0,5)){const name=String(raw?.name??'attachment.bin').replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,180)||'attachment.bin';const type=String(raw?.type??'application/octet-stream').slice(0,100);const size=Number(raw?.size??0);const data=String(raw?.dataBase64??'');if(!Number.isFinite(size)||size<0||size>MAX_ONE||total+size>MAX_TOTAL)throw Object.assign(new Error('Размер вложений превышает лимит'),{statusCode:413});if(!data)continue;const buf=Buffer.from(data,'base64');if(buf.length!==size||buf.length>MAX_ONE||total+buf.length>MAX_TOTAL)throw Object.assign(new Error('Некорректное вложение'),{statusCode:422});const id=randomUUID();const storageName=`${id}.bin`;await writeFile(join(ATTACHMENTS_DIR,storageName),buf,{flag:'wx'});db.prepare('INSERT INTO support_attachments(id,ticket_id,message_id,original_name,mime_type,size_bytes,storage_name,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,ticketId,messageId,name,type,buf.length,storageName,new Date().toISOString());total+=buf.length;}}
export async function readAttachment(ownerId,attachmentId){const db=await database();ownerId=user(ownerId);const row=db.prepare(`SELECT a.* FROM support_attachments a JOIN support_tickets t ON t.id=a.ticket_id WHERE a.id=? AND t.owner_id=?`).get(attachmentId,ownerId);if(!row)throw Object.assign(new Error('Вложение не найдено'),{statusCode:404});return row;}
