import {normalizeGroupList,cleanSubject,cleanLocation,cleanTeacher,normalizeStream,timeRange,typeFrom,parseWeekSpec,normalizeHalf,isoDate} from './normalize.mjs';

const ANCHOR_MONDAY='2026-08-31';
const DAYS={пн:1,понедельник:1,вт:2,вторник:2,ср:3,среда:3,чт:4,четверг:4,пт:5,пятница:5,сб:6,суббота:6,вс:7,воскресенье:7};
function addDays(date,n){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function mondayFromWeek(week){return addDays(ANCHOR_MONDAY,(week-1)*7);}
function dayFromText(value){const s=String(value??'').toLowerCase();for(const [k,v] of Object.entries(DAYS))if(new RegExp(`(?:^|\\s)${k}(?=\\s|$|\\d|[.,])`).test(s))return v;return null;}
function dateFromText(value){const s=String(value??'').trim();const m=s.match(/(?:^|\\D)(\\d{1,2})[./](\\d{1,2})[./](\\d{4})(?:\\D|$)/);return m?isoDate(`${m[1]}.${m[2]}.${m[3]}`):isoDate(s);}
function expandDates(day,weeks,date){if(date)return[date];if(!day||!weeks.length)return[];return weeks.map(w=>addDays(mondayFromWeek(w),day-1));}
export function matrixWithMerges(ws,XLSX){const range=XLSX.utils.decode_range(ws['!ref']??'A1');const grid=[];for(let r=range.s.r;r<=range.e.r;r++){const row=[];for(let c=range.s.c;c<=range.e.c;c++){const cell=ws[XLSX.utils.encode_cell({r,c})];row.push(String(cell?.w??cell?.v??'').replace(/\s+/g,' ').trim());}grid.push(row);}for(const merge of (ws['!merges']??[])){const top=ws[XLSX.utils.encode_cell({r:merge.s.r,c:merge.s.c})];const value=String(top?.w??top?.v??'').replace(/\s+/g,' ').trim();for(let r=merge.s.r;r<=merge.e.r;r++)for(let c=merge.s.c;c<=merge.e.c;c++){const rr=r-range.s.r,cc=c-range.s.c;if(!grid[rr]||grid[rr][cc])continue;grid[rr][cc]=value;}}return grid;}
function detectGroupColumns(grid){const cols=new Map();for(let r=0;r<Math.min(12,grid.length);r++)for(let c=0;c<(grid[r]?.length??0);c++){for(const g of normalizeGroupList(grid[r][c]))if(/^\d{3,4}[А-ЯA-Z]{0,3}$/i.test(g)&&!cols.has(c))cols.set(c,g);}return cols;}
function makeEvent({program,course,source,group,stream,date,tr,cell,rowText,idx}){const subject=cleanSubject(cell.replace(/(?:ауд(?:итория)?\\.?\\s*[\\w./-]+|корпус\\s*[\\w./-]+)/ig,' ').replace(/\\b(?:лекция|пз|практика|лабораторная|семинар)\\b/ig,' '));if(!subject||subject.length<2)return null;const lm=cell.match(/(?:ауд(?:итория)?\\.?\\s*[\\w./-]+|корпус\\s*[\\w./-]+)/i);const tm=cell.match(/(?:преподаватель|доцент|профессор|ассистент|преп\\.?)[ :]+([^;|]+)/i);return{id:`${program}-${course}-${group}-${date}-${tr.start}-${idx}`,program,course,group,stream,date,start:tr.start,end:tr.end,subject,location:cleanLocation(lm?.[0]??''),teacher:cleanTeacher(tm?.[1]??''),type:typeFrom(cell,rowText),half:normalizeHalf(cell),weeks:(/(?:недел|нед\.?|week|числител|знаменател)/i.test(cell)?parseWeekSpec(cell):[]).length?`нед. ${parseWeekSpec(cell).join(', ')}`:undefined,sourceUrl:source.url,sourceTitle:source.title,sourceKind:'official-xlsx',confidence:.74};}

export async function parseOfficialXlsx(buffer,{program,course,source}){const XLSX=await import('xlsx');const wb=XLSX.read(buffer,{type:'buffer',cellDates:true});const events=[];const warnings=[];for(const name of wb.SheetNames){const grid=matrixWithMerges(wb.Sheets[name],XLSX);if(!grid.length){warnings.push(`${name}: пустой лист`);continue;}const header=grid.slice(0,10).flat().join(' ');const stream=normalizeStream(header)||source.stream||null;const groupCols=detectGroupColumns(grid);if(!groupCols.size)warnings.push(`${name}: группы не определены; fallback ALL с датами`);let currentDay=null,currentDate='';let currentWeeks=[];for(let r=0;r<grid.length;r++){const row=grid[r]??[];const rowText=row.join(' ');const day=dayFromText(rowText);if(day){currentDay=day;const date=dateFromText(rowText);currentDate=date??'';}else{const date=dateFromText(rowText);if(date)currentDate=date;}if(/(?:недел|нед\.?|week|числител|знаменател)/i.test(rowText)){const ws=parseWeekSpec(rowText);if(ws.length)currentWeeks=ws;}const tr=timeRange(rowText);if(!tr)continue;const dates=expandDates(currentDay,currentWeeks,currentDate);if(!dates.length)continue;if(groupCols.size){for(const [col,group] of groupCols){const cell=row[col]??'';if(!cell||cleanText(cell)===group)continue;for(const d of dates){const e=makeEvent({program,course,source,group,stream,date:d,tr,cell,rowText,idx:events.length});if(e)events.push(e);}}}else{for(const d of dates){for(const cell of row){if(!cell||cell===row[0])continue;const e=makeEvent({program,course,source,group:'ALL',stream,date:d,tr,cell,rowText,idx:events.length});if(e)events.push(e);}}}}}if(!events.length)warnings.push('XLSX parser: не удалось извлечь событий');return{events,warnings,specialty:program,source};}
