import type {Course,EventStatus,ProgramCode,ScheduleEvent,Task,UserProfile} from './core/types.js';
import {PROGRAMS,sourceFor,sourcesFor} from './data/catalog.js';
import {groupsFor,streamForGroup} from './data/roster.js';
import {mondayOf,weekDates,formatDateRu,longDateRu,sameDay,addDays,todayISO} from './core/date.js';
import {eventAppliesToGroup,filterEvents} from './core/filter.js';
import {loadSchedule,clearScheduleMemory} from './services/scheduleService.js';
import {addTask,readTasks,removeTask,updateTask} from './services/taskService.js';
import {applyTheme,cycleTheme,initTheme,themeMode} from './ui/theme.js';
import {FAQ} from './ui/faq.js';
import {createPersonalEvent,deletePersonalEvent,listPersonalEvents,updatePersonalEvent,type EventInput,type PersonalEvent} from './services/eventService.js';
import {fileToAttachment} from './services/supportService.js';
import {createTicket,listTickets,getTicket,addTicketMessage,type SupportTicket} from './services/supportService.js';
import {localDate,localDateTimeToUtc,localTime,userTimeZone,localDateTimeInput} from './core/time.js';
import {scheduleToCalendarEvent,type CalendarEvent} from './core/calendar.js';

const DAYS=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const STATUS_LABEL:Record<EventStatus,string>={planned:'Запланировано',confirmed:'Подтверждено',in_progress:'В процессе',completed:'Завершено',cancelled:'Отменено'};
const VIEW_LABEL={day:'День',workweek:'Рабочая неделя',week:'Неделя',month:'Месяц',agenda:'Agenda',list:'Список'} as const;
type ViewMode=keyof typeof VIEW_LABEL;
const DEFAULT_PROFILE:UserProfile={program:'31.05.01',course:1,group:'123'};
const initial=readInitialProfile();
const state={profile:initial,week:mondayOf(todayISO(userTimeZone())),focusDate:todayISO(userTimeZone()),events:[] as CalendarEvent[],official:[] as ScheduleEvent[],personal:[] as PersonalEvent[],status:'loading' as string,message:'Подготавливаем расписание…',search:'',type:'all',statusFilter:'all',categoryFilter:'all',page:'schedule',tasks:readTasks(),theme:themeMode(),faqQuery:'',faqCategory:'Все',view:'week' as ViewMode,timezone:readTimezone(),double1:'#4b81da',double2:'#73e0c4',editingId:'',draft:false,undo:null as null|{id:string;before:EventInput;scope:'single'|'series'|'following';kind:'update'|'delete'},ticketList:[] as SupportTicket[],ticketSelected:'',supportStatus:'idle' as 'idle'|'loading'|'ready'|'error'};

function $(id:string){const el=document.getElementById(id);if(!el)throw new Error(`Missing #${id}`);return el;}
function esc(v:string){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]!));}
function groupOptions(program:ProgramCode,course:Course){const groups=groupsFor(program,course);return groups.length?groups:[''];}
function ensureProfile(){const groups=groupsFor(state.profile.program,state.profile.course);if(!groups.length){state.profile.group='';return;}if(!groups.includes(state.profile.group))state.profile.group=groups[0]!;}
function readInitialProfile():UserProfile{try{const params=new URLSearchParams(location.search);const raw=JSON.parse(localStorage.getItem('almazov.profile')??'null') as Record<string,unknown>|null;const stored=raw&&typeof raw==='object'?raw:{};const programValue=params.get('program')??String(stored.program??'');const courseValue=params.get('course')??String(stored.course??'');const groupValue=params.get('group')??String(stored.group??'');const program=PROGRAMS.some(x=>x.code===programValue)?programValue as ProgramCode:DEFAULT_PROFILE.program;const n=Number(courseValue);const course=Number.isInteger(n)&&n>=1&&n<=6?n as Course:DEFAULT_PROFILE.course;return{program,course,group:String(groupValue)};}catch{return {...DEFAULT_PROFILE};}}
function readTimezone(){return localStorage.getItem('almazov.timezone')||userTimeZone();}
function setTimezone(zone:string){try{new Intl.DateTimeFormat('en-US',{timeZone:zone}).format();localStorage.setItem('almazov.timezone',zone);state.timezone=zone;}catch{throw new Error('Некорректный часовой пояс');}}
function startOfWeek(d:string){return mondayOf(d);}
function monthStart(d:string){return `${d.slice(0,7)}-01`;}
function monthEnd(d:string){const x=new Date(`${monthStart(d)}T00:00:00Z`);x.setUTCMonth(x.getUTCMonth()+1);x.setUTCDate(0);return x.toISOString().slice(0,10);}
function rangeDates():{from:string;to:string;dates:string[]}{
  if(state.view==='day'){return{from:state.focusDate,to:state.focusDate,dates:[state.focusDate]};}
  if(state.view==='workweek'){const m=startOfWeek(state.focusDate);const dates=weekDates(m).slice(0,5);return{from:dates[0]!,to:dates[4]!,dates};}
  if(state.view==='month'){const from=monthStart(state.focusDate);const to=monthEnd(state.focusDate);const first=startOfWeek(from);const last=addDays(startOfWeek(to),6);const dates:string[]=[];for(let d=first;d<=last;d=addDays(d,1))dates.push(d);return{from,to,dates};}
  const dates=weekDates(startOfWeek(state.focusDate));return{from:dates[0]!,to:dates[6]!,dates:state.view==='agenda'||state.view==='list'?dates:dates};
}
function localMidnightUtc(date:string){return localDateTimeToUtc(`${date}T00:00`,state.timezone);}
function getDisplayEvents():CalendarEvent[]{
  const selected=state.official.filter(e=>eventAppliesToGroup(e,{...state.profile,stream:streamForGroup(state.profile.program,state.profile.group)})).map(e=>scheduleToCalendarEvent(e,state.timezone));
  const personal=state.personal.map(e=>({id:e.id,kind:'personal' as const,title:e.title,description:e.description??'',category:e.category,status:e.status,startAt:e.startAt,endAt:e.endAt,timeZone:e.timeZone,allDay:e.allDay,location:e.location??'',meetingUrl:e.meetingUrl,attendees:e.attendees,recurrence:e.recurrence,seriesId:e.seriesId,readOnly:false}));const combined:CalendarEvent[]=[...selected,...personal];
  return combined.filter(e=>{
    if(state.search&&!`${e.title??(('subject' in e)?e.subject:'')} ${e.location??''} ${e.teacher??''} ${e.category??''}`.toLowerCase().includes(state.search.toLowerCase()))return false;
    if(state.type!=='all'&&e.type!==state.type)return false;
    if(state.statusFilter!=='all'&&(e.status??'planned')!==state.statusFilter)return false;
    if(state.categoryFilter!=='all'&&(e.category??'personal')!==state.categoryFilter)return false;
    return true;
  }).sort((a,b)=>a.startAt.localeCompare(b.startAt)||String(a.title??a.subject).localeCompare(String(b.title??b.subject),'ru'));
}
async function reloadEvents(){
  state.status='loading';state.message='Загружаем расписание и личные события…';renderSchedule();
  const result=await loadSchedule(state.profile.program,state.profile.course);state.official=result.events;state.status=result.status;state.message=result.message;
  const range=rangeDates();const from=localMidnightUtc(range.from);const to=localMidnightUtc(addDays(range.to,1));
  try{state.personal=await listPersonalEvents(from,to);}catch(error){state.personal=[];state.message+=` Личные события не загружены: ${error instanceof Error?error.message:'ошибка'}`;}
}
export async function boot(){initTheme();loadAppearance();applyAppearance();ensureProfile();renderShell();bind();render();await reloadEvents();render();}
function render(){renderShell();renderProfileOptions();renderSchedule();renderTasks();renderFaculties();renderResources();renderKug();renderFaq(state.faqQuery);renderHome();renderSupport();renderSettings();renderProfilePage();}
function nav(page:string){state.page=page;document.querySelectorAll<HTMLElement>('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll<HTMLElement>('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('pageTitle').textContent={home:'Главная',schedule:'Расписание',homework:'Задачи',kug:'КУГ',resources:'Материалы',faculties:'Факультеты',faq:'FAQ',support:'Поддержка',settings:'Настройки',profilePage:'Профиль'}[page]??'Almazov';document.body.classList.remove('menu-open');if(page==='schedule')renderSchedule();if(page==='homework')renderTasks();if(page==='faq')renderFaq(state.faqQuery);if(page==='home')renderHome();if(page==='support')loadSupport();if(page==='settings')renderSettings();if(page==='profilePage')renderProfilePage();}
function renderShell(){const p=PROGRAMS.find(x=>x.code===state.profile.program);$('profileName').textContent=state.profile.group?`Группа ${state.profile.group}`:p?.shortTitle??'Профиль';$('profileMeta').textContent=`${p?.title??''} · ${state.profile.course} курс${streamForGroup(state.profile.program,state.profile.group)?` · поток ${streamForGroup(state.profile.program,state.profile.group)}`:''}`;$('syncLabel').textContent=state.message;$('statusDot').className=`${state.status==='live'?'ok':state.status==='cache'?'cache':state.status==='loading'?'loading':'bad'}`;}
function renderHome(){const events=getDisplayEvents();const today=state.focusDate;const weekEvents=events.filter(e=>{const d=localDate(e.startAt,state.timezone);return d>=startOfWeek(today)&&d<=addDays(startOfWeek(today),6)});const upcoming=weekEvents.filter(e=>localDate(e.startAt,state.timezone)>=today).slice(0,5);$('homeContext').textContent=state.profile.group?`${PROGRAMS.find(p=>p.code===state.profile.program)?.title} · ${state.profile.course} курс · группа ${state.profile.group}`:'Выберите группу';$('homeStats').innerHTML=[['Занятий сегодня',String(weekEvents.filter(e=>localDate(e.startAt,state.timezone)===today).length)],['На неделе',String(weekEvents.length)],['Личные события',String(state.personal.length)],['Источник',state.status==='live'?'LIVE':state.status==='cache'?'CACHE':'OFFLINE']].map(([a,b])=>`<div class="stat-card"><span>${a}</span><b>${b}</b></div>`).join('');$('homeUpcoming').innerHTML=upcoming.length?upcoming.map(e=>`<article class="next-item"><div><span>${longDateRu(localDate(e.startAt,state.timezone))} · ${localTime(e.startAt,state.timezone)}</span><b>${esc(String(e.title??(('subject' in e)?e.subject:'')))}</b><small>${esc(e.location||'Без места')}</small></div><button class="btn small" data-open-event="${esc(e.id)}">Открыть</button></article>`).join(''):`<div class="empty-state compact card"><div class="empty-icon">◷</div><h3>Ближайших событий нет</h3><p>Создайте личную встречу или откройте другой период.</p></div>`;}
function renderSchedule(){
  $('emptyState')?.remove();
  const events=getDisplayEvents();const range=rangeDates();
  $('weekLabel').textContent=state.view==='month'?`${formatDateRu(monthStart(state.focusDate))} — ${formatDateRu(monthEnd(state.focusDate))}`:`${formatDateRu(range.from)} — ${formatDateRu(range.to)}`;
  $('weekSubLabel').textContent=`${PROGRAMS.find(p=>p.code===state.profile.program)?.shortTitle??''} · ${state.profile.course} курс${state.profile.group?` · группа ${state.profile.group}`:''} · ${state.timezone}`;
  $('scheduleCount').textContent=`${events.length} событий`;
  document.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  const dates=range.dates.length?range.dates:weekDates(startOfWeek(state.focusDate));
  $('weekStrip').innerHTML=dates.slice(0,31).map((d,i)=>`<button class="day-pill ${d===todayISO(state.timezone)?'is-today':''}" data-jump-date="${d}"><span>${DAYS[i%7]}</span><b>${d.slice(8,10)}</b><em>${events.filter(e=>localDate(e.startAt,state.timezone)===d).length}</em></button>`).join('');
  const html=state.view==='month'?renderMonth(events):state.view==='agenda'?renderAgenda(events):state.view==='list'?renderList(events):renderTimeGrid(events,dates);
  $('desktopSchedule').innerHTML=html;$('mobileSchedule').innerHTML=state.view==='month'?html:renderMobile(events,dates);
  $('dataHealthTitle').textContent=state.status==='live'?'Источник актуален':state.status==='cache'?'Локальный snapshot':state.status==='loading'?'Загрузка…':state.status==='partial'?'Частичные данные':'Источник недоступен';$('dataHealthText').textContent=`${state.message} Часовой пояс интерфейса: ${state.timezone}.`;
  ($('sourceLink') as HTMLAnchorElement).href=sourceFor(state.profile.program,state.profile.course);($('statusText') as HTMLElement).textContent=state.status.toUpperCase();
  if(state.status==='loading')$('desktopSchedule').innerHTML=renderSkeleton();
  if(state.status!=='loading'&&!events.length&&!state.personal.length){const el=document.createElement('div');el.id='emptyState';el.className='empty-state card';el.innerHTML=`<div class="empty-icon">∅</div><h3>В этом периоде нет событий</h3><p>Проверьте фильтры или создайте личное событие.</p><div class="empty-actions"><button class="btn primary" data-action="new-event">Создать событие</button><a class="btn" href="${sourceFor(state.profile.program,state.profile.course)}" target="_blank" rel="noopener noreferrer">Официальный источник ↗</a></div>`;$('scheduleRoot').appendChild(el);}
}
function renderSkeleton(){return `<div class="calendar-skeleton">${Array.from({length:7},(_,i)=>`<div><span></span><i></i><i></i><i></i></div>`).join('')}</div>`;}
function visibleSegments(events:CalendarEvent[],date:string){return events.filter(e=>{const s=localDate(e.startAt,state.timezone),end=localDate(e.endAt,state.timezone);return s<=date&&end>=date;});}
function layoutForDay(list:CalendarEvent[],date:string){const day=visibleSegments(list,date);const decorated=day.map(e=>{const startDate=localDate(e.startAt,state.timezone),endDate=localDate(e.endAt,state.timezone);const st=startDate===date?localTime(e.startAt,state.timezone):'00:00';const en=endDate===date?localTime(e.endAt,state.timezone):'24:00';return{e,sm:timeMinutes(st),em:timeMinutes(en)}}).sort((a,b)=>a.sm-b.sm||a.em-b.em);const lanes:number[]=[];const result:Array<{e:CalendarEvent;sm:number;em:number;lane:number}>=[];for(const item of decorated){let lane=0;let occupied=lanes[lane];while(occupied!==undefined&&occupied>item.sm){lane++;occupied=lanes[lane];}lanes[lane]=item.em;result.push({...item,lane});}return result.map(x=>({...x,total:Math.max(...result.filter(r=>r.sm<x.em&&r.em>x.sm).map(r=>r.lane+1),x.lane+1)}));}
function timeMinutes(v:string){if(v==='24:00')return 1440;const [h,m]=v.split(':').map(Number);return (h||0)*60+(m||0);}
function renderTimeGrid(events:CalendarEvent[],dates:string[]){const start=420,px=1.15;const labels=Array.from({length:17},(_,i)=>`${String(7+i).padStart(2,'0')}:00`);return `<div class="time-grid" style="--day-count:${dates.length}"><div class="time-axis">${labels.map((l,i)=>`<span style="top:${i*60*px}px">${l}</span>`).join('')}</div><div class="time-days">${dates.map((date,i)=>{const dayEvents=visibleSegments(events,date);const allDay=dayEvents.filter(e=>e.allDay);const laid=layoutForDay(dayEvents.filter(e=>!e.allDay),date);return `<section class="time-day ${date===todayISO(state.timezone)?'today':''}" data-drop-date="${date}"><header><span>${DAYS[i%7]}</span><b>${date.slice(8,10)} ${new Intl.DateTimeFormat('ru-RU',{month:'short'}).format(new Date(`${date}T12:00:00Z`)).replace('.','')}</b></header>${allDay.length?`<div class="all-day-strip">${allDay.map(e=>`<button class="all-day-event ${e.kind==='personal'?'personal':''}" data-open-event="${esc(e.id)}"><span>Весь день</span><strong>${esc(String(e.title??(('subject' in e)?e.subject:'')))}</strong></button>`).join('')}</div>`:''}<div class="time-canvas">${Array.from({length:17},(_,n)=>`<i class="hour-line" style="top:${n*60*px}px"></i>`).join('')}${laid.map((x)=>{const top=Math.max(0,(x.sm-start)*px),height=Math.max(42,(x.em-x.sm)*px);const width=100/x.total,left=x.lane*width;return eventHtml(x.e,date,top,height,left,width);}).join('')}${date===todayISO(state.timezone)?currentTimeLine(px,start):''}</div></section>`;}).join('')}</div></div>`;}
function currentTimeLine(px:number,start:number){const now=new Date();const tm=new Intl.DateTimeFormat('en-US',{timeZone:state.timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now).split(':').map(Number);const hh=Number(tm[0]??0),mm=Number(tm[1]??0);const top=((hh*60+mm)-start)*px;if(top<0||top>1100)return '';return `<div class="current-time" style="top:${top}px"><i></i><b>Сейчас</b></div>`;}
function eventHtml(e:CalendarEvent,date:string,top:number,height:number,left:number,width:number){const isPersonal=e.kind==='personal';const title=e.title??(('subject' in e)?e.subject:'');const st=e.allDay?'Весь день':localDate(e.startAt,state.timezone)===date?localTime(e.startAt,state.timezone):'00:00';const en=e.allDay?'':localDate(e.endAt,state.timezone)===date?localTime(e.endAt,state.timezone):'24:00';const status=e.status??(isPersonal?'planned':undefined);const draggable=isPersonal?' draggable="true"':'';return `<article class="calendar-event ${isPersonal?'personal':'official'} status-${status??'planned'}" data-event-id="${esc(e.id)}" data-event-kind="${e.kind}"${draggable} tabindex="0" style="top:${top}px;height:${height}px;left:${left}%;width:${width}%;"><div class="event-accent"></div><div class="event-time">${esc(st)}–${esc(en)}</div><strong>${esc(String(title))}</strong><div class="event-meta">${esc(isPersonal?(e.category||'Личное'):(e.type==='practice'?'ПЗ':e.type==='lecture'?'Лекция':'Занятие'))}${e.location?` · ${esc(e.location)}`:''}</div>${status?`<span class="event-status">${STATUS_LABEL[status]}</span>`:''}${isPersonal?'<button class="resize-handle" data-resize-event="true" aria-label="Изменить длительность"></button>':''}</article>`;}
function renderMobile(events:CalendarEvent[],dates:string[]){return `<div class="mobile-days">${dates.map((d,i)=>`<section class="mobile-day ${d===todayISO(state.timezone)?'today':''}" data-drop-date="${d}"><header><div><span>${DAYS[i%7]}</span><h3>${longDateRu(d)}</h3></div><b>${visibleSegments(events,d).length}</b></header><div class="mobile-event-list">${visibleSegments(events,d).map(e=>{const st=localDate(e.startAt,state.timezone)===d?localTime(e.startAt,state.timezone):'00:00';const en=localDate(e.endAt,state.timezone)===d?localTime(e.endAt,state.timezone):'24:00';return `<button class="mobile-event ${e.kind==='personal'?'personal':''}" data-open-event="${esc(e.id)}"><span>${st}–${en}</span><strong>${esc(String(e.title??(('subject' in e)?e.subject:'')))}</strong><small>${esc(e.location||'')} ${e.kind==='personal'?'· личное':'· официальное'}</small></button>`;}).join('')||'<div class="day-empty">Свободный день</div>'}</div></section>`).join('')}</div>`;}
function renderMonth(events:CalendarEvent[]){const from=startOfWeek(monthStart(state.focusDate));const to=addDays(startOfWeek(monthEnd(state.focusDate)),6);const dates=[];for(let d=from;d<=to;d=addDays(d,1))dates.push(d);return `<div class="month-grid">${DAYS.map(d=>`<div class="month-head">${d}</div>`).join('')}${dates.map(d=>`<button class="month-cell ${d.slice(0,7)!==state.focusDate.slice(0,7)?'muted-month':''} ${d===todayISO(state.timezone)?'today':''}" data-jump-date="${d}"><span>${d.slice(8,10)}</span><div>${visibleSegments(events,d).slice(0,4).map(e=>`<em class="month-event ${e.kind==='personal'?'personal':''}">${localTime(e.startAt,state.timezone)} ${esc(String(e.title??(('subject' in e)?e.subject:'')))}</em>`).join('')}</div>${visibleSegments(events,d).length>4?`<small>+${visibleSegments(events,d).length-4}</small>`:''}</button>`).join('')}</div>`;}
function renderAgenda(events:CalendarEvent[]){const dates=rangeDates().dates;return `<div class="agenda-list">${dates.flatMap(d=>visibleSegments(events,d).map(e=>({d,e}))).sort((a,b)=>a.e.startAt.localeCompare(b.e.startAt)).map(({d,e})=>`<article class="agenda-item card"><time>${esc(longDateRu(d))}<br><b>${localTime(e.startAt,state.timezone)}</b></time><div><span class="eyebrow">${e.kind==='personal'?'Личное':'Официальное'}</span><h3>${esc(String(e.title??(('subject' in e)?e.subject:'')))}</h3><p>${esc(e.location||'Без места')} · ${e.category?esc(e.category):e.type}</p></div><div><span class="status-badge">${STATUS_LABEL[e.status??'planned']}</span>${e.kind==='personal'?`<button class="btn small" data-open-event="${esc(e.id)}">Открыть</button>`:''}</div></article>`).join('')||'<div class="empty-state card"><h3>Пустая повестка</h3><p>В выбранном периоде нет событий.</p></div>'}</div>`;}
function renderList(events:CalendarEvent[]){return `<div class="event-table card"><div class="table-head"><span>Дата</span><span>Время</span><span>Событие</span><span>Тип</span><span>Статус</span></div>${events.map(e=>`<div class="table-row"><span>${esc(localDate(e.startAt,state.timezone))}</span><span>${esc(localTime(e.startAt,state.timezone))}–${esc(localTime(e.endAt,state.timezone))}</span><strong>${esc(String(e.title??(('subject' in e)?e.subject:'')))}</strong><span>${e.kind==='personal'?'Личное':e.type}</span><span>${STATUS_LABEL[e.status??'planned']}</span></div>`).join('')||'<div class="empty-table">Нет событий</div>'}</div>`;}
function renderTasks(){state.tasks=readTasks();$('taskCount').textContent=String(state.tasks.filter(x=>!x.done).length);$('taskList').innerHTML=state.tasks.length?state.tasks.map(t=>`<article class="task-row ${t.done?'done':''}"><button class="task-check" data-task-toggle="${esc(t.id)}">${t.done?'✓':''}</button><div class="task-body"><b>${esc(t.subject)}</b><p>${esc(t.text)}</p><small>${t.due?`Дедлайн: ${esc(t.due)}`:'Без дедлайна'}</small></div><div class="task-actions"><button class="btn small danger" data-task-delete="${esc(t.id)}">Удалить</button></div></article>`).join(''):`<div class="empty-state card"><div class="empty-icon">✓</div><h3>Задач пока нет</h3><p>Создайте первую задачу для текущей группы.</p><button class="btn primary" data-action="add-task">Создать задачу</button></div>`;}
function renderFaculties(){$('facultyGrid').innerHTML=PROGRAMS.map(p=>{const published=p.publishedCourses.length;return `<article class="faculty-card card"><span class="eyebrow">${p.code}</span><h3>${esc(p.title)}</h3><p>${esc(p.faculty)}</p><div class="faculty-tags"><span>1–6 курсы</span><span>${published}/6 опубликовано</span></div><button class="btn small primary" data-pick-program="${p.code}">Открыть расписание</button></article>`;}).join('');}
function renderResources(){const grouped=PROGRAMS.flatMap(p=>p.scheduleCourses.map(course=>({p,course,sources:sourcesFor(p.code,course)})));$('resourceList').innerHTML=grouped.map(({p,course,sources})=>{const published=sources.filter(s=>s.status==='published'||s.status==='verified');const status=!p.publishedCourses.includes(course)?'Не опубликовано':published.length?'Источник доступен':'Требуется серверный импорт';return `<article class="resource-card card"><div class="meta"><span class="eyebrow">${p.code} · ${course} курс</span><b>${esc(p.title)}</b><p>${published.length?published.map(s=>esc(s.title)).join(' · '):'Официальная страница / parser adapter'}</p></div><div><span class="resource-status">${status}</span><div style="height:6px"></div><a class="btn small" href="${sourceFor(p.code,course)}" target="_blank" rel="noopener noreferrer">Источник ↗</a></div></article>`;}).join('');}
function renderKug(){$('kugContext').textContent=`${state.profile.course} курс · ${state.profile.group||'группа не выбрана'}`;}
function renderFaq(filter=''){const q=filter.trim().toLowerCase();const items=FAQ.filter(x=>(state.faqCategory==='Все'||x.category===state.faqCategory)&&(`${x.question} ${x.answer}`).toLowerCase().includes(q));$('faqCategories').innerHTML=['Все',...Array.from(new Set(FAQ.map(x=>x.category)))].map(c=>`<button class="chip-button ${c===state.faqCategory?'active':''}" data-faq-category="${esc(c)}">${esc(c)}</button>`).join('');$('faqPopular').innerHTML=FAQ.filter(x=>x.popular).slice(0,4).map(x=>`<button class="faq-popular" data-faq-open="${esc(x.id)}"><b>${esc(x.question)}</b><small>${esc(x.category)}</small></button>`).join('');$('faqList').innerHTML=items.length?items.map(x=>`<details id="faq-${esc(x.id)}"><summary>${esc(x.question)}<span>+</span></summary><p>${esc(x.answer)}</p></details>`).join(''):`<div class="empty-state compact card"><h3>Ничего не найдено</h3><p>Попробуйте изменить запрос или категорию.</p><button class="btn" data-page="support">Обратиться в поддержку</button></div>`;}
function renderSettings(){const tz=$('settingsTimezone') as HTMLSelectElement;if(tz){const common=['Europe/Zurich','Europe/Moscow','Europe/London','Europe/Berlin','Asia/Tokyo','America/New_York','America/Los_Angeles','UTC'];tz.innerHTML=Array.from(new Set([...common,state.timezone])).map(z=>`<option value="${z}">${z}</option>`).join('');tz.value=state.timezone;}const theme=$('settingsTheme') as HTMLSelectElement;if(theme)theme.value=themeMode();}
function renderProfilePage(){const p=PROGRAMS.find(x=>x.code===state.profile.program);$('profileSummary').innerHTML=`<div class="profile-large"><div class="avatar large">A</div><div><h2>Профиль студента</h2><p>${esc(p?.title??'')} · ${state.profile.course} курс · группа ${esc(state.profile.group||'не выбрана')}</p><small>Часовой пояс календаря: ${esc(state.timezone)}</small></div></div><div class="profile-grid"><div class="card profile-stat"><span>Программа</span><b>${esc(p?.shortTitle??state.profile.program)}</b></div><div class="card profile-stat"><span>Группа</span><b>${esc(state.profile.group||'—')}</b></div><div class="card profile-stat"><span>Источник</span><b>${state.status.toUpperCase()}</b></div></div>`;}
async function loadSupport(){if(state.supportStatus==='loading')return;state.supportStatus='loading';renderSupport();try{state.ticketList=await listTickets();state.supportStatus='ready';if(state.ticketSelected)await loadTicketDetail(state.ticketSelected);}catch{state.supportStatus='error';}renderSupport();}
async function loadTicketDetail(id:string){try{const t=await getTicket(id);state.ticketList=[...state.ticketList.filter(x=>x.id!==id),t];state.ticketSelected=id;}catch{state.ticketSelected='';}}
function renderSupport(){const list=$('ticketList');const selected=state.ticketList.find(x=>x.id===state.ticketSelected);if(state.supportStatus==='loading'){list.innerHTML=renderSkeletonCards(3);$('ticketDetail').innerHTML='<div class="empty-state card"><p>Загружаем обращения…</p></div>';}else if(state.supportStatus==='error'){list.innerHTML='<div class="empty-state card"><h3>Не удалось загрузить обращения</h3><button class="btn" data-action="support-retry">Повторить</button></div>';$('ticketDetail').innerHTML='';}else{list.innerHTML=state.ticketList.length?state.ticketList.map(t=>`<button class="ticket-row ${t.id===state.ticketSelected?'active':''}" data-ticket="${esc(t.id)}"><span>${esc(t.number)}</span><b>${esc(t.subject)}</b><small>${ticketStatusLabel(t.status)} · ${new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium'}).format(new Date(t.updatedAt))}</small></button>`).join(''):'<div class="empty-state compact"><h3>Обращений пока нет</h3><p>Создайте тикет, если FAQ не помог.</p></div>';if(selected){$('ticketDetail').innerHTML=`<article class="ticket-detail card"><div class="ticket-head"><div><span class="eyebrow">${esc(selected.number)}</span><h2>${esc(selected.subject)}</h2><p>${ticketStatusLabel(selected.status)} · ${esc(selected.priority)}</p></div><button class="btn small" data-action="support-close">Закрыть</button></div><div class="message-list">${(selected.messages??[]).map(m=>`<div class="message ${m.authorType==='support'?'support':''}"><b>${m.authorType==='support'?'Поддержка':'Вы'}</b><p>${esc(m.body)}</p><small>${new Date(m.createdAt).toLocaleString('ru-RU')}</small></div>`).join('')}</div><form id="ticketReplyForm" class="reply-form"><textarea id="ticketReply" rows="4" placeholder="Добавить сообщение…" aria-label="Ответ по тикету"></textarea><button class="btn primary" type="submit">Отправить</button></form></article>`;}else $('ticketDetail').innerHTML='<div class="empty-state card"><h3>Выберите обращение</h3><p>Или создайте новое.</p></div>';}}
function ticketStatusLabel(s:SupportTicket['status']){return({new:'Новое',in_progress:'В работе',waiting_user:'Ожидает ответа',resolved:'Решено',closed:'Закрыто'} as Record<string,string>)[s]??s;}
function renderSkeletonCards(n:number){return `<div class="skeleton-stack">${Array.from({length:n},()=>'<div class="skeleton-card"></div>').join('')}</div>`;}
function openModal(id:string){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.classList.add('modal-open');const focus=$(id).querySelector<HTMLElement>('button,select,input,textarea');focus?.focus();}
function closeModal(id:string){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
function loadAppearance(){try{const raw=JSON.parse(localStorage.getItem('almazov.appearance')??'null') as Record<string,unknown>|null;const valid=(v:unknown,fallback:string)=>typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v)?v:fallback;state.double1=valid(raw?.double1,state.double1);state.double2=valid(raw?.double2,state.double2);}catch{}}
function applyAppearance(){document.documentElement.style.setProperty('--double1',state.double1);document.documentElement.style.setProperty('--double2',state.double2);}
function saveAppearance(){localStorage.setItem('almazov.appearance',JSON.stringify({double1:state.double1,double2:state.double2}));applyAppearance();}
function renderProfileOptions(){const ps=$('programSelect') as HTMLSelectElement,cs=$('courseSelect') as HTMLSelectElement,gs=$('groupSelect') as HTMLSelectElement;ps.innerHTML=PROGRAMS.map(p=>`<option value="${p.code}">${esc(p.title)} · ${p.code}</option>`).join('');cs.innerHTML=([1,2,3,4,5,6] as Course[]).map(c=>`<option value="${c}">${c} курс</option>`).join('');gs.innerHTML=groupOptions(state.profile.program,state.profile.course).map(g=>g?`<option value="${esc(g)}">${esc(g)}</option>`:`<option value="">— группы не опубликованы —</option>`).join('');ps.value=state.profile.program;cs.value=String(state.profile.course);gs.value=state.profile.group;fillModalOptions(state.profile.program,state.profile.course,state.profile.group);}
function fillModalOptions(program:ProgramCode,course:Course,group:string){const p=$('modalProgram') as HTMLSelectElement,c=$('modalCourse') as HTMLSelectElement,g=$('modalGroup') as HTMLSelectElement;p.innerHTML=PROGRAMS.map(x=>`<option value="${x.code}">${esc(x.title)}</option>`).join('');c.innerHTML=([1,2,3,4,5,6] as Course[]).map(x=>`<option value="${x}">${x} курс</option>`).join('');g.innerHTML=groupOptions(program,course).map(x=>`<option value="${esc(x)}">${esc(x||'—')}</option>`).join('');p.value=program;c.value=String(course);g.value=group;}
async function saveProfile(){const p=($('modalProgram') as HTMLSelectElement).value as ProgramCode,c=Number(($('modalCourse') as HTMLSelectElement).value) as Course,g=($('modalGroup') as HTMLSelectElement).value;state.profile={program:p,course:c,group:g};ensureProfile();localStorage.setItem('almazov.profile',JSON.stringify(state.profile));saveAppearance();closeModal('profileModal');state.week=mondayOf(state.focusDate);state.focusDate=state.week;clearScheduleMemory();render();await reloadEvents();render();}
function openTask(){($('taskSubject') as HTMLInputElement).value='';($('taskText') as HTMLTextAreaElement).value='';($('taskDate') as HTMLInputElement).value='';$('taskNotice').textContent='';openModal('taskModal');}
function saveTask(){const subject=($('taskSubject') as HTMLInputElement).value.trim(),text=($('taskText') as HTMLTextAreaElement).value.trim();if(!subject||!text){$('taskNotice').textContent='Заполните предмет и задание.';return;}addTask({id:crypto.randomUUID(),subject,text,due:($('taskDate') as HTMLInputElement).value||undefined,done:false,...state.profile,createdAt:new Date().toISOString()});closeModal('taskModal');renderTasks();}
function readEventForm():EventInput|null{const title=($('eventTitle') as HTMLInputElement).value.trim(),start=($('eventStart') as HTMLInputElement).value,end=($('eventEnd') as HTMLInputElement).value,tz=($('eventTimezone') as HTMLSelectElement).value;if(!title){setEventNotice('Введите название события.');return null;}if(!start||!end){setEventNotice('Укажите начало и окончание.');return null;}try{const startAt=localDateTimeToUtc(start,tz),endAt=localDateTimeToUtc(end,tz);if(Date.parse(endAt)<=Date.parse(startAt)){setEventNotice('Окончание должно быть позже начала.');return null;}const freq=($('eventRepeat') as HTMLSelectElement).value;const recurrence=freq==='none'?null:{frequency:freq as NonNullable<EventInput['recurrence']>['frequency'],interval:Number(($('eventInterval') as HTMLInputElement).value||1),until:(($('eventUntil') as HTMLInputElement).value)||null,weekdays:Array.from(document.querySelectorAll<HTMLInputElement>('[data-weekday]:checked')).map(x=>Number(x.dataset.weekday))};return{title,description:($('eventDescription') as HTMLTextAreaElement).value.trim(),category:($('eventCategory') as HTMLSelectElement).value,status:($('eventStatus') as HTMLSelectElement).value as EventStatus,startAt,endAt,timeZone:tz,allDay:($('eventAllDay') as HTMLInputElement).checked,location:($('eventLocation') as HTMLInputElement).value.trim(),meetingUrl:($('eventMeeting') as HTMLInputElement).value.trim(),attendees:($('eventAttendees') as HTMLInputElement).value.split(',').map(x=>x.trim()).filter(Boolean),privacy:($('eventPrivacy') as HTMLSelectElement).value as 'private'|'public',recurrence};}catch(error){setEventNotice(error instanceof Error?error.message:'Некорректные данные');return null;}}
function setEventNotice(msg:string){$('eventNotice').textContent=msg;}
function saveDraft(){const ids=['eventTitle','eventStart','eventEnd','eventTimezone','eventRepeat','eventInterval','eventUntil','eventCategory','eventStatus','eventLocation','eventMeeting','eventAttendees','eventPrivacy','eventDescription','eventAllDay'];const obj:Record<string,string|boolean>={};for(const id of ids){const el=document.getElementById(id) as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|null;if(el)obj[id]=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:el.value;}localStorage.setItem('almazov.event.draft',JSON.stringify(obj));}
function restoreDraft(){try{const raw=JSON.parse(localStorage.getItem('almazov.event.draft')??'{}') as Record<string,unknown>;for(const [id,v] of Object.entries(raw)){const el=document.getElementById(id) as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|null;if(!el)continue;if(el instanceof HTMLInputElement&&el.type==='checkbox')el.checked=v===true;else el.value=String(v??'');}}catch{}}
function clearDraft(){localStorage.removeItem('almazov.event.draft');}
function fillEventModal(e?:CalendarEvent|PersonalEvent,date?:string){const tz=$('eventTimezone') as HTMLSelectElement;const scopeWrap=$('eventEditScopeWrap');const scope=$('eventEditScope') as HTMLSelectElement;tz.innerHTML=[state.timezone,'Europe/Moscow','UTC','Europe/Berlin','America/New_York','Asia/Tokyo'].filter((x,i,a)=>a.indexOf(x)===i).map(x=>`<option value="${x}">${x}</option>`).join('');state.editingId=e?.kind==='personal'?e.id:'';state.draft=!e;scopeWrap.hidden=!(e?.kind==='personal'&&!!e.recurrence);scope.value='series';if(e){($('eventTitle') as HTMLInputElement).value=e.title??(('subject' in e)?e.subject:'');($('eventStart') as HTMLInputElement).value=localDateTimeInput(e.startAt,e.timeZone||state.timezone);($('eventEnd') as HTMLInputElement).value=localDateTimeInput(e.endAt,e.timeZone||state.timezone);tz.value=e.timeZone||state.timezone;($('eventDescription') as HTMLTextAreaElement).value=e.description??'';($('eventCategory') as HTMLSelectElement).value=e.category??'personal';($('eventStatus') as HTMLSelectElement).value=e.status??'planned';($('eventLocation') as HTMLInputElement).value=e.location??'';($('eventMeeting') as HTMLInputElement).value=e.meetingUrl??'';($('eventAttendees') as HTMLInputElement).value=(e.attendees??[]).join(', ');($('eventPrivacy') as HTMLSelectElement).value=e.privacy??'private';($('eventAllDay') as HTMLInputElement).checked=!!e.allDay;($('eventRepeat') as HTMLSelectElement).value=e.recurrence?.frequency??'none';($('eventInterval') as HTMLInputElement).value=String(e.recurrence?.interval??1);($('eventUntil') as HTMLInputElement).value=e.recurrence?.until??'';scopeWrap.hidden=!e.recurrence;}else{const start=date?`${date}T09:00`:state.focusDate+'T09:00';const end=date?`${date}T10:00`:state.focusDate+'T10:00';($('eventTitle') as HTMLInputElement).value='';($('eventStart') as HTMLInputElement).value=start;($('eventEnd') as HTMLInputElement).value=end;tz.value=state.timezone;($('eventDescription') as HTMLTextAreaElement).value='';($('eventCategory') as HTMLSelectElement).value='personal';($('eventStatus') as HTMLSelectElement).value='planned';($('eventLocation') as HTMLInputElement).value='';($('eventMeeting') as HTMLInputElement).value='';($('eventAttendees') as HTMLInputElement).value='';($('eventPrivacy') as HTMLSelectElement).value='private';($('eventAllDay') as HTMLInputElement).checked=false;($('eventRepeat') as HTMLSelectElement).value='none';($('eventInterval') as HTMLInputElement).value='1';($('eventUntil') as HTMLInputElement).value='';restoreDraft();}setEventNotice('');$('eventModalTitle').textContent=e?'Редактировать событие':'Новое событие';openModal('eventModal');}
function detectConflict(input:EventInput,ignoreId=''){return getDisplayEvents().filter(e=>e.kind==='schedule'||e.id!==ignoreId).some(e=>Date.parse(input.endAt)>Date.parse(e.startAt)&&Date.parse(input.startAt)<Date.parse(e.endAt));}
async function saveEvent(){const input=readEventForm();if(!input)return;if(detectConflict(input,state.editingId)){const ok=confirm('Событие пересекается с другим событием. Всё равно сохранить?');if(!ok)return;}try{const wasEditing=!!state.editingId;if(state.editingId){const current=state.personal.find(x=>x.id===state.editingId);const before=current?toInput(current):input;const scope=((document.getElementById('eventEditScope') as HTMLSelectElement|null)?.value??'series') as 'single'|'following'|'series';const updated=await updatePersonalEvent(state.editingId,input,scope);state.undo={id:updated.id,before,scope,kind:'update'};}else{await createPersonalEvent(input);}clearDraft();closeModal('eventModal');state.editingId='';await reloadEvents();render();showUndo(wasEditing?'Изменение сохранено':'Событие создано');}catch(error){setEventNotice(error instanceof Error?error.message:'Не удалось сохранить событие.');}}
function toInput(e:PersonalEvent):EventInput{return{title:e.title,description:e.description,category:e.category,status:e.status,startAt:e.startAt,endAt:e.endAt,timeZone:e.timeZone,allDay:e.allDay,location:e.location,meetingUrl:e.meetingUrl,attendees:e.attendees,privacy:e.privacy,recurrence:e.recurrence??null};}
async function deleteSelected(id:string){const e=state.personal.find(x=>x.id===id);if(!e)return;if(!confirm('Удалить личное событие?'))return;const before=toInput(e);try{await deletePersonalEvent(id,e.seriesId?'series':'single');state.undo={id,before,scope:e.seriesId?'series':'single',kind:'delete'};await reloadEvents();render();showUndo('Событие удалено');}catch(error){toast(error instanceof Error?error.message:'Не удалось удалить событие','error');}}
let undoTimer:number|undefined;function showUndo(text:string){const root=document.getElementById('toastRoot');if(!root)return;root.innerHTML=`<div class="toast"><span>${esc(text)}</span><button class="btn small" data-action="undo">Отменить</button></div>`;if(undoTimer)window.clearTimeout(undoTimer);undoTimer=window.setTimeout(()=>{root.innerHTML='';state.undo=null;},7000);}
async function undo(){const u=state.undo;if(!u)return;try{if(u.kind==='delete'){const created=await createPersonalEvent(u.before);state.undo={...u,id:created.id};}else await updatePersonalEvent(u.id,u.before,'series');state.undo=null;if(undoTimer)window.clearTimeout(undoTimer);$('toastRoot').innerHTML='';await reloadEvents();render();}catch(error){toast(error instanceof Error?error.message:'Не удалось отменить действие','error');}}
function toast(text:string,kind:'success'|'error'='success'){$('toastRoot').innerHTML=`<div class="toast ${kind}">${esc(text)}</div>`;window.setTimeout(()=>{$('toastRoot').innerHTML='';},5000);}
function openEventById(id:string){const e=state.events.find(x=>x.id===id);if(!e)return;if(e.kind==='personal'){fillEventModal(e);}else{openEventDetail(e);}}
function openEventDetail(e:CalendarEvent){$('detailTitle').textContent=String(e.title??(('subject' in e)?e.subject:''));$('detailBody').innerHTML=`<div class="detail-grid"><span>Дата</span><b>${esc(longDateRu(localDate(e.startAt,state.timezone)))}</b><span>Время</span><b>${esc(localTime(e.startAt,state.timezone))}–${esc(localTime(e.endAt,state.timezone))}</b><span>Часовой пояс</span><b>${esc(state.timezone)}</b><span>Тип</span><b>${esc(e.kind==='personal'?'Личное':String(e.type??'Занятие'))}</b><span>Место</span><b>${esc(e.location||'—')}</b><span>Статус</span><b>${esc(STATUS_LABEL[e.status??'planned'])}</b><span>Описание</span><p>${esc(e.description||'—')}</p></div>${e.kind==='personal'?'<div class="detail-actions"><button class="btn primary" data-action="edit-opened">Изменить</button><button class="btn danger" data-action="delete-opened">Удалить</button></div>':''}`;state.editingId=e.kind==='personal'?e.id:'';openModal('eventDetailModal');}
async function handleSupportSubmit(form:HTMLFormElement){const subject=($('ticketSubject') as HTMLInputElement).value.trim(),description=($('ticketDescription') as HTMLTextAreaElement).value.trim();if(subject.length<3||description.length<5){$('ticketNotice').textContent='Заполните тему и подробное описание.';return;}const files=Array.from(($('ticketFiles') as HTMLInputElement).files??[]);try{const attachments=await Promise.all(files.slice(0,5).map(fileToAttachment));const t=await createTicket({subject,description,category:($('ticketCategory') as HTMLSelectElement).value,priority:($('ticketPriority') as HTMLSelectElement).value,attachments});state.ticketList=[t,...state.ticketList.filter(x=>x.id!==t.id)];state.ticketSelected=t.id;form.reset();$('ticketNotice').textContent='';renderSupport();toast(`Обращение ${t.number} создано`);}catch(error){$('ticketNotice').textContent=error instanceof Error?error.message:'Не удалось создать тикет.';}}
function bind(){
 document.addEventListener('click',async e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-action],[data-page],[data-view],[data-pick-program],[data-task-delete],[data-task-toggle],[data-jump-date],[data-open-event],[data-ticket],[data-faq-category],[data-faq-open]');if(!target)return;const action=target.dataset.action;
  if(target.dataset.page){nav(target.dataset.page);return;}if(target.dataset.view){state.view=target.dataset.view as ViewMode;renderSchedule();await reloadEvents();render();return;}if(target.dataset.faqCategory){state.faqCategory=target.dataset.faqCategory;renderFaq(state.faqQuery);return;}if(target.dataset.faqOpen){document.getElementById(`faq-${target.dataset.faqOpen}`)?.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById(`faq-${target.dataset.faqOpen}`)?.setAttribute('open','');return;}if(target.dataset.ticket){state.ticketSelected=target.dataset.ticket;await loadTicketDetail(state.ticketSelected);renderSupport();return;}if(target.dataset.openEvent){openEventById(target.dataset.openEvent);return;}
  if(action==='toggle-menu'){document.body.classList.toggle('menu-open');return;}if(action==='theme'){cycleTheme();state.theme=themeMode();renderSettings();return;}if(action==='today'){state.focusDate=todayISO(state.timezone);state.week=mondayOf(state.focusDate);await reloadEvents();render();return;}if(action==='prev-period'){state.focusDate=state.view==='month'?addDays(state.focusDate,-30):addDays(state.focusDate,state.view==='day'?-1:-7);state.week=mondayOf(state.focusDate);await reloadEvents();render();return;}if(action==='next-period'){state.focusDate=state.view==='month'?addDays(state.focusDate,30):addDays(state.focusDate,state.view==='day'?1:7);state.week=mondayOf(state.focusDate);await reloadEvents();render();return;}if(action==='refresh-data'){clearScheduleMemory();await reloadEvents();render();return;}if(action==='new-event'){fillEventModal(undefined,target.dataset.jumpDate);return;}if(action==='save-event'){await saveEvent();return;}if(action==='close-modal'){closeModal('profileModal');closeModal('eventModal');closeModal('taskModal');closeModal('eventDetailModal');return;}if(action==='profile'){openModal('profileModal');return;}if(action==='save-profile'){await saveProfile();return;}if(action==='add-task'){openTask();return;}if(action==='close-task'){closeModal('taskModal');return;}if(action==='save-task'){saveTask();return;}if(action==='share-week'){await shareLink();return;}if(action==='export-ics'){exportICS();return;}if(action==='print-schedule'){window.print();return;}if(action==='undo'){await undo();return;}if(action==='edit-opened'){const e=state.personal.find(x=>x.id===state.editingId);closeModal('eventDetailModal');if(e)fillEventModal(e);return;}if(action==='delete-opened'){const id=state.editingId;closeModal('eventDetailModal');await deleteSelected(id);return;}if(action==='support-new'){openModal('ticketModal');return;}if(action==='support-retry'){state.supportStatus='idle';await loadSupport();return;}if(action==='support-close'){state.ticketSelected='';renderSupport();return;}if(action==='save-settings'){try{setTimezone(($('settingsTimezone') as HTMLSelectElement).value);applyTheme(($('settingsTheme') as HTMLSelectElement).value as 'light'|'dark'|'system');toast('Настройки сохранены');await reloadEvents();render();}catch(error){toast(error instanceof Error?error.message:'Не удалось сохранить настройки','error');}return;}
  if(target.dataset.pickProgram){state.profile.program=target.dataset.pickProgram as ProgramCode;state.profile.course=1;state.profile.group=groupsFor(state.profile.program,1)[0]??'';localStorage.setItem('almazov.profile',JSON.stringify(state.profile));state.focusDate=todayISO(state.timezone);state.week=mondayOf(state.focusDate);clearScheduleMemory();nav('schedule');await reloadEvents();render();return;}
  if(target.dataset.taskDelete){removeTask(target.dataset.taskDelete);renderTasks();return;}if(target.dataset.taskToggle){const tt=readTasks().find(x=>x.id===target.dataset.taskToggle);if(tt)updateTask(tt.id,{done:!tt.done});renderTasks();return;}if(target.dataset.jumpDate){state.focusDate=target.dataset.jumpDate;state.week=mondayOf(state.focusDate);if(state.view==='month'){}else state.view='day';renderSchedule();await reloadEvents();render();return;}
 });
 document.addEventListener('submit',async e=>{if(e.target instanceof HTMLFormElement){if(e.target.id==='ticketForm'){e.preventDefault();await handleSupportSubmit(e.target);}if(e.target.id==='ticketReplyForm'){e.preventDefault();const id=state.ticketSelected;const body=($('ticketReply') as HTMLTextAreaElement).value.trim();if(id&&body){const t=await addTicketMessage(id,body);state.ticketList=state.ticketList.map(x=>x.id===id?t:x);renderSupport();}}}});
 document.addEventListener('input',e=>{const t=e.target as HTMLInputElement|HTMLTextAreaElement;if(t.closest('#eventModal')){saveDraft();}if(t.id==='scheduleSearch'){state.search=t.value;renderSchedule();}if(t.id==='faqSearch'){state.faqQuery=t.value;renderFaq(t.value);}if(t.id==='double1'){state.double1=t.value;saveAppearance();}if(t.id==='double2'){state.double2=t.value;saveAppearance();}});
 ['programSelect','courseSelect','groupSelect'].forEach(id=>$(id).addEventListener('change',async()=>{if(id==='programSelect'||id==='courseSelect')renderProfileOptions();applySelectProfile();}));
 document.querySelectorAll<HTMLElement>('#typeFilter [data-type]').forEach(b=>b.addEventListener('click',()=>{state.type=b.dataset.type??'all';document.querySelectorAll<HTMLElement>('#typeFilter [data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSchedule();}));
 $('statusFilter').addEventListener('change',e=>{state.statusFilter=(e.target as HTMLSelectElement).value;renderSchedule();});$('categoryFilter').addEventListener('change',e=>{state.categoryFilter=(e.target as HTMLSelectElement).value;renderSchedule();});
 ['eventStart','eventEnd','eventTimezone'].forEach(id=>$(id).addEventListener('change',()=>{const tz=($('eventTimezone') as HTMLSelectElement).value; if(id==='eventTimezone'){const s=($('eventStart') as HTMLInputElement),en=($('eventEnd') as HTMLInputElement);if(s.value&&en.value){/* values remain in selected zone by design */}}setEventNotice('');}));
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('scheduleSearch').focus();}if(e.key==='Escape'){['profileModal','eventModal','taskModal','eventDetailModal','ticketModal'].forEach(closeModal);}});
 document.addEventListener('dragstart',e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('.calendar-event');if(t?.dataset.eventKind==='personal'&&e.dataTransfer){e.dataTransfer.setData('text/event-id',t.dataset.eventId??'');e.dataTransfer.effectAllowed='move';}});
 document.addEventListener('dragover',e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('[data-drop-date]');if(t)e.preventDefault();});
 document.addEventListener('drop',async e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('[data-drop-date]');if(!t)return;e.preventDefault();const id=e.dataTransfer?.getData('text/event-id');if(!id)return;const ev=state.personal.find(x=>x.id===id);if(!ev)return;const old=toInput(ev);const date=t.dataset.dropDate!;const startInput=localDateTimeInput(ev.startAt,ev.timeZone);const endInput=localDateTimeInput(ev.endAt,ev.timeZone);const ns=localDateTimeToUtc(`${date}T${startInput.slice(11)}`,ev.timeZone),ne=localDateTimeToUtc(`${date}T${endInput.slice(11)}`,ev.timeZone);const next={...old,startAt:ns,endAt:ne};try{await updatePersonalEvent(id,next,'single');state.undo={id,before:old,scope:'single',kind:'update'};await reloadEvents();render();showUndo('Событие перенесено');}catch(error){toast(error instanceof Error?error.message:'Не удалось перенести событие','error');}});
 document.addEventListener('pointerdown',e=>{const t=(e.target as HTMLElement).closest<HTMLElement>('[data-resize-event]');if(!t)return;const eventEl=t.closest<HTMLElement>('.calendar-event');const id=eventEl?.dataset.eventId;const ev=id?state.personal.find(x=>x.id===id):undefined;if(!ev||!eventEl)return;e.preventDefault();const startY=e.clientY,base=toInput(ev),baseEnd=Date.parse(ev.endAt);const move=(ev2:PointerEvent)=>{const min=Math.max(15,Math.round((baseEnd-Date.parse(base.startAt))/60000+((ev2.clientY-startY)/1.15)/15)*15);eventEl.style.height=`${Math.max(42,min*1.15)}px`;};const up=async(ev2:PointerEvent)=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const duration=Math.max(15,Math.round((baseEnd-Date.parse(base.startAt))/60000+((ev2.clientY-startY)/1.15)/15)*15);const end=new Date(Date.parse(base.startAt)+duration*60000).toISOString();try{await updatePersonalEvent(id!,{...base,endAt:end},'single');state.undo={id:id!,before:base,scope:'single',kind:'update'};await reloadEvents();render();showUndo('Длительность изменена');}catch(error){toast(error instanceof Error?error.message:'Не удалось изменить длительность','error');}};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true});});
}
async function applySelectProfile(){const p=$('programSelect') as HTMLSelectElement,c=$('courseSelect') as HTMLSelectElement,g=$('groupSelect') as HTMLSelectElement;state.profile={program:p.value as ProgramCode,course:Number(c.value) as Course,group:g.value||''};ensureProfile();localStorage.setItem('almazov.profile',JSON.stringify(state.profile));state.focusDate=todayISO(state.timezone);state.week=mondayOf(state.focusDate);state.events=[];state.status='loading';clearScheduleMemory();render();await reloadEvents();render();}
async function shareLink(){const url=new URL(location.href);url.search='';url.searchParams.set('program',state.profile.program);url.searchParams.set('course',String(state.profile.course));if(state.profile.group)url.searchParams.set('group',state.profile.group);try{await navigator.clipboard.writeText(url.toString());toast('Ссылка скопирована');}catch{toast(url.toString());}}
function exportICS(){const events=getDisplayEvents();const tz=state.timezone;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Almazov Schedule Hub//RU','CALSCALE:GREGORIAN'];for(const e of events){const start=new Date(e.startAt).toISOString().replaceAll('-','').replaceAll(':','').replace(/\.\d{3}Z$/,'Z');const end=new Date(e.endAt).toISOString().replaceAll('-','').replaceAll(':','').replace(/\.\d{3}Z$/,'Z');lines.push('BEGIN:VEVENT',`UID:${escapeICS(e.id)}@almazov-hub`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${escapeICS(String(e.title??(('subject' in e)?e.subject:'')))}`,`DESCRIPTION:${escapeICS(e.description??'')}`,`LOCATION:${escapeICS(e.location??'')}`,'END:VEVENT');}lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`almazov-${state.profile.group||'group'}-${state.focusDate}-${tz.replaceAll('/','_')}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function escapeICS(v:string){return v.replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n');}
